version: '3.9'

services:
  server-dependencies:
    image: node:20.9.0
    container_name: server-dependencies
    working_dir: /server
    volumes:
      - ./server:/server
    command: npm install

  client-dependencies:
    image: node:20.9.0
    container_name: client-dependencies
    working_dir: /client
    volumes:
      - ./client:/client
    command: npm install

  client:
    image: node:20.9.0
    container_name: client
    working_dir: /client
    network_mode: host
    volumes:
      - ./client:/client
    ports:
      - 5173:5173
    depends_on:
      server:
        condition: service_started
      client-dependencies:
        condition: service_completed_successfully
    command: npm run dev

  server:
    image: node:20.9.0
    container_name: server
    working_dir: /server
    network_mode: host
    volumes:
      - ./server:/server
    ports:
      - 5000:5000
    depends_on:
      mongo:
        condition: service_started
      server-dependencies:
        condition: service_completed_successfully
    command: npm run dev

  mongo:
    image: mongo:7.0.4-rc0
    container_name: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: tasks
    volumes: 
      - ./db:/data/db
      - ./db/log:/var/log/mongodb/ 
    
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: secret
      ME_CONFIG_BASICAUTH_USERNAME: sa
      ME_CONFIG_BASICAUTH_PASSWORD: sa
      ME_CONFIG_MONGODB_URL: mongodb://root:secret@mongo:27017/
    links:
      - mongo


