version: '3.9'

services:
  server-dependencies:
    image: node:20.9.0
    container_name: server-dependencies
    working_dir: /server
    volumes:
      - ./server:/server
    command: npm install

  client-dependencies:
    image: node:20.9.0
    container_name: client-dependencies
    working_dir: /client
    volumes:
      - ./client:/client
    command: npm install

  client:
    image: node:20.9.0
    container_name: client
    working_dir: /client
    volumes:
      - ./client:/client
    ports:
      - 5173:5173
    depends_on:
      server:
        condition: service_started
      client-dependencies:
        condition: service_completed_successfully
    command: npm run dev

  server:
    image: node:20.9.0
    container_name: server
    working_dir: /server
    volumes:
      - ./server:/server
    ports:
      - 5000:5000
    depends_on:
      server-dependencies:
        condition: service_completed_successfully
    command: npm run dev


